routes:
- endpoint: hello
  methods:
  - GET
  response:
    message: Hello, Mock Server!
  status: 200
- endpoint: status
  methods:
  - GET
  response:
    message: available
    status: ok
  status: 200
